'use client';
import {useEffect,useState} from 'react';
import {ArrowUpRight,CheckCircle2} from 'lucide-react';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
const options=['Website design','NDIS & allied health','E-commerce','SEO & digital marketing','AI automation','Website audit','Not sure yet'];
export function ContactForm(){const [service,setService]=useState('');const [status,setStatus]=useState('');const [busy,setBusy]=useState(false);const [sent,setSent]=useState(false);const [id,setId]=useState('');
useEffect(()=>{const s=new URLSearchParams(window.location.search).get('service');if(s&&options.includes(s))setService(s);setId(typeof crypto.randomUUID==='function'?crypto.randomUUID():'10000000-1000-4000-8000-100000000000'.replace(/[018]/g,c=>(Number(c)^crypto.getRandomValues(new Uint8Array(1))[0]&15>>Number(c)/4).toString(16)));},[]);
useEffect(()=>{const context=(document as any).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();try{Promise.resolve(context.registerTool({name:'select_enquiry_service',title:'Select enquiry service',description:'Select a service in the visible enquiry form. This only prepares the form; it does not send an enquiry.',inputSchema:{type:'object',properties:{service:{type:'string',enum:options}},required:['service'],additionalProperties:false},annotations:{readOnlyHint:false},execute(input:unknown){const value=(input as any)?.service;if(typeof value!=='string'||!options.includes(value))throw new Error('Choose a listed service.');setService(value);return {service:value,status:'selected',submitted:false};}},{signal:lifecycle.signal})).catch(()=>{});}catch{}return ()=>lifecycle.abort();},[]);
async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(!service){setStatus('Please select a service so we can direct your enquiry.');return;}setBusy(true);setStatus('');const data=Object.fromEntries(new FormData(e.currentTarget));try{const r=await fetch('/api/enquiries',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...data,service,id})});const result=await r.json() as {error?:string};if(!r.ok)throw new Error(result.error||'Your enquiry could not be saved. Please try again.');setSent(true);}catch(err){setStatus(err instanceof Error?err.message:'Please try again, or email info@swiftdigitals.com.au.');}finally{setBusy(false);}}
if(sent)return <div className="form-success" role="status"><CheckCircle2 size={42}/><h3>Your enquiry has been received.</h3><p>Thank you for telling us about your project. Keep your reference below if you contact us about this enquiry.</p><p className="reference">Reference: {id.slice(0,8).toUpperCase()}</p><a href="tel:+61469785113" className="text-link">Prefer to talk? Call 0469 785 113</a></div>;
return <form className="contact-form" onSubmit={submit}><div className="form-row"><label>Name <span>*</span><input name="name" autoComplete="name" placeholder="Your name" required maxLength={100}/></label><label>Email <span>*</span><input name="email" type="email" autoComplete="email" placeholder="you@company.com.au" required maxLength={254}/></label></div><div className="form-row"><label>Phone <small>(optional)</small><input name="phone" type="tel" autoComplete="tel" placeholder="Your phone number" maxLength={40}/></label><label>Website <small>(optional)</small><input name="website" autoComplete="url" placeholder="Your website address" maxLength={500}/></label></div><div className="field"><label id="service-label">What can we help with? <span>*</span></label><Select value={service} onValueChange={value=>{if(value)setService(value)}} name="service"><SelectTrigger className="service-select" aria-labelledby="service-label" aria-required="true"><SelectValue placeholder="Select a service"/></SelectTrigger><SelectContent>{options.map(s=><SelectItem key={s} value={s}>{s}</SelectItem>)}</SelectContent></Select></div><label>What would you like to achieve? <span>*</span><textarea name="message" placeholder="A little about your business, your project and what you want to improve…" rows={5} required minLength={10} maxLength={5000}/></label><div className="honeypot" aria-hidden="true"><label>Leave this field empty<input name="company_url" tabIndex={-1} autoComplete="off"/></label></div><p className="form-note">Please don’t include sensitive health, financial or identity information.</p>{status&&<p role="alert" className="form-error">{status}</p>}<div className="form-bottom"><button className="button" disabled={busy} type="submit">{busy?'Sending…':'Send Enquiry'}<ArrowUpRight size={17}/></button><p>Your details are used to respond to your enquiry.<br/><a href="/privacy">View privacy information</a></p></div></form>}
