import {ArrowUpRight,Monitor,Users,ShoppingBag,ChartNoAxesCombined,Workflow,Check,Smartphone,FileText,Mail,Calendar,ShieldCheck,Settings,MapPin,Phone,MousePointer2,Search,Layers,SlidersHorizontal} from 'lucide-react';
import type {ReactNode} from 'react';
export const iconMap:any={monitor:Monitor,people:Users,bag:ShoppingBag,chart:ChartNoAxesCombined,workflow:Workflow,check:Check,phone:Smartphone,file:FileText,mail:Mail,calendar:Calendar,shield:ShieldCheck,settings:Settings,pin:MapPin,call:Phone,cursor:MousePointer2,search:Search,layers:Layers,sliders:SlidersHorizontal};
export function Icon({name,size=28}:{name:string;size?:number}){const C=iconMap[name]||Monitor;return <C size={size} strokeWidth={1.5} aria-hidden="true"/>}
export function Button({href,children,secondary=false}:{href:string;children:ReactNode;secondary?:boolean}){return <a className={`button ${secondary?'button-secondary':''}`} href={href}>{children}<ArrowUpRight size={17}/></a>}
export function Eyebrow({children}:{children:ReactNode}){return <p className="eyebrow">{children}</p>}
export function SectionHeading({eyebrow,title,text}:{eyebrow?:string;title:string;text?:string}){return <div className="section-heading"><div>{eyebrow&&<Eyebrow>{eyebrow}</Eyebrow>}<h2>{title}</h2></div>{text&&<p>{text}</p>}</div>}
export function Faq({items,title='Before we get started.'}:{items:string[][];title?:string}){return <section className="section"><div className="container faq-layout"><div><Eyebrow>Frequently asked questions</Eyebrow><h2>{title}</h2></div><div>{items.map(([q,a])=><details className="faq" key={q}><summary>{q}<span aria-hidden="true">+</span></summary><p>{a}</p></details>)}</div></div></section>}
export function Cta({title='Let’s make your next step a clear one.',text='Tell us about your business and what you’d like to improve.',button='Discuss Your Project',href='/contact'}:{title?:string;text?:string;button?:string;href?:string}){return <section className="cta"><div className="container cta-inner"><div><Eyebrow>Ready when you are</Eyebrow><h2>{title}</h2><p>{text}</p></div><Button href={href}>{button}</Button></div></section>}
export function Steps({ai=false}:{ai?:boolean}){const items=ai?[['Map the task','Understand the process, the people involved and where time is being lost.'],['Agree the rules','Define the information, permissions and points for human review.'],['Build & test','Test the workflow with realistic examples before putting it to work.'],['Review & improve','Agree how to monitor outcomes and handle changes over time.']]:[['Discover','We learn about your business, your goals and your customers.'],['Plan','We map the structure, content and features your website needs.'],['Design & build','We create a clear design and bring the agreed website to life.'],['Launch & handover','We test the key journeys and guide you through the next steps.']];return <section className="section"><div className="container"><Eyebrow>A clear path from idea to launch</Eyebrow><div className="steps">{items.map(([t,d],i)=><article key={t}><span className="step-number">0{i+1}</span><h3>{t}</h3><p>{d}</p></article>)}</div></div></section>}
export function Showcase({compact=false}:{compact?:boolean}){return <section className="section lavender"><div className="container"><SectionHeading eyebrow="Illustrative design concepts" title="A look at the possibilities." text="Two different directions. Thoughtful examples of how a business can look and feel online."/><div className="showcase-grid"><figure><img src="/assets/health-concept.webp" alt="Illustrative Harbour Health website concept with sage green design and clear allied health service information" width="1536" height="1024" loading="lazy"/><figcaption><div><h3>Harbour Health</h3><p>Allied health website concept</p></div><span className="tag">Concept</span></figcaption></figure><figure><img src="/assets/store-concept.webp" alt="Illustrative The Shelf online homewares store concept with warm neutral styling and ceramics" width="1536" height="1024" loading="lazy"/><figcaption><div><h3>The Shelf</h3><p>E-commerce website concept</p></div><span className="tag">Concept</span></figcaption></figure></div>{!compact&&<p className="caption">These are illustrative design concepts, not commissioned client projects or evidence of business results.</p>}</div></section>}
export function WorkflowPreview(){return <div className="workflow-preview"><div className="workflow-top"><span className="status-dot"/>An enquiry, organised.<span className="tag">Illustrative workflow</span></div><div className="workflow-body"><div className="workflow-sidebar"><span className="active">Enquiries <b>3</b></span><span>Customer intake</span><span>Ready for review</span><span>Completed</span></div><div className="workflow-main"><p className="small-label">NEW ENQUIRY</p><h3>A little more context.<br/>A better conversation.</h3><div className="intake-row"><Icon name="file" size={20}/><div><strong>Information collected</strong><p>Services, timing and project details</p></div><Check size={16}/></div><div className="intake-row"><Icon name="workflow" size={20}/><div><strong>Details organised</strong><p>Ready for your team to review</p></div><Check size={16}/></div><div className="review-pill"><Icon name="people" size={18}/>Your team makes the next call</div></div></div></div>}
